// Tidal Flat Identification - Unified Pipeline
// Applicable to all years 2014-2024 (Asset-based)
// Only change: YEAR, ASSET_PATH, and sample collections

// 1. Parameters - modify these for each year
// For 2014-2017 (Landsat 8):  change ASSET_PATH and use _early samples (Step 6)
// For 2018-2024 (Sentinel-2): change ASSET_PATH and use standard samples (Step 6)

var YEAR      = 2014;
var ELEV_MAX  = 10;
var NDVI_VEG  = 0.4;
var MIN_PATCH = 500;

var studyArea  = ee.FeatureCollection(
  "projects/my-project-20260224-488410/assets/LYG_Final"
);
var ASSET_PATH = "projects/my-project-20260224-488410/assets/LYG_TimeSeries_Stacks_1/LYG_Stack_" + YEAR;

Map.setCenter(119.22, 34.60, 10);
Map.centerObject(studyArea, 11);

// 2. Load pre-processed feature package and build feature stack
// All sensor differences resolved at data package generation stage
var img = ee.Image(ASSET_PATH).float();

var inundFreqRaw = img.select('inund_freq');
var maxNDVI      = img.select('NDVI');

var featureStack = img.select([
  'B2','B3','B4','B5','B6','B7',
  'NDVI','mNDWI','NDWI',
  'inund_freq',
  'edge_density',
  'nir_stdDev',
  'dist_water',
  'elevation'
]).float();

// 3. Physical constraints: DEM and vegetation masks
var dem         = ee.Image('USGS/SRTMGL1_003').clip(studyArea);
var lowLand     = dem.lte(ELEV_MAX);
var denseVeg    = maxNDVI.gt(NDVI_VEG);
var notDenseVeg = denseVeg.not().or(maxNDVI.unmask(0).not());

// 4. Load Murray Baseline
// Union of v1 (2014-2016 classification) and v2 (2019 probability >50%)
var murrayV1 = ee.ImageCollection('UQ/murray/Intertidal/v1_1/global_intertidal')
  .filterDate('2014-01-01', '2017-01-01')
  .first().select('classification').clip(studyArea);
var murrayV2  = ee.Image('JCU/Murray/GIC/global_tidal_wetland_change/2019');
var murrayEnd = murrayV2.select('twprobabilityEnd').gt(50).clip(studyArea);
var murrayUnion = murrayV1.or(murrayEnd).updateMask(lowLand);

// 5. Murray baseline: morphological cleaning and small patch removal (MIN_PATCH=500px)
// focal_max then focal_min fills internal voids and restores boundary
// Removes isolated Murray patches smaller than 500 pixels
var tidalFlatRaw = murrayUnion.updateMask(lowLand).clip(studyArea);
var k = ee.Kernel.circle({radius: 1, units: 'pixels'});
var cleaned = tidalFlatRaw
  .focal_max({kernel: k, iterations: 1})
  .focal_min({kernel: k, iterations: 1});
var connMurray = cleaned.selfMask()
  .connectedPixelCount({maxSize: MIN_PATCH + 1, eightConnected: true});
var tidalFlatClean = cleaned.updateMask(connMurray.gte(MIN_PATCH));

// 6. Dynamic extension: capture tidal flats outside Murray baseline
// inund_freq threshold [0.05, 0.6): excludes permanent water and dry land
// validCount proxy: inundFreqRaw.mask() used as valid-observation filter
// (validCount not stored in package; mask() presence indicates valid data)
// NDVI < 0.2: strict vegetation exclusion to prevent cropland contamination
// Restricted to areas outside Murray baseline boundary
var validCount   = img.select('valid_count');
var freqValid    = inundFreqRaw
  .updateMask(lowLand)
  .updateMask(validCount.gte(10)); 
var freqDetected = freqValid.gte(0.05).and(freqValid.lt(0.6));
var strictVeg    = maxNDVI.lt(0.2);

var freqExtension = freqDetected
  .and(murrayUnion.unmask(0).not())
  .and(strictVeg)
  .updateMask(lowLand)
  .clip(studyArea);

// Remove isolated dynamic extension patches smaller than 25 pixels
var connExt = freqExtension.selfMask()
  .connectedPixelCount({maxSize: 26, eightConnected: true});
freqExtension = freqExtension.updateMask(connExt.gte(25));

// 7. Merge baseline and extension, then morphological smoothing
// Erosion (focal_min) breaks false narrow connections between patches
// Dilation (focal_max x2) fills internal gaps and smooths boundaries
// Final erosion restores approximate original boundary extent
// Remove debris patches smaller than 40 pixels generated by smoothing
var mergedRaw = tidalFlatClean.unmask(0).or(freqExtension.unmask(0));

var k_clean = ee.Kernel.circle({radius: 2});
var mergedCleaned = mergedRaw
  .focal_min({kernel: k_clean, iterations: 1})
  .focal_max({kernel: k_clean, iterations: 1})
  .focal_max({kernel: k_clean, iterations: 1})
  .focal_min({kernel: k_clean, iterations: 1});

// Remove debris patches smaller than 40 pixels generated during smoothing
var mergedConn = mergedCleaned.selfMask()
  .connectedPixelCount({maxSize: 41, eightConnected: true});
var mergedBeforeRF = mergedCleaned.updateMask(mergedConn.gte(40));

// 8. Random Forest Classification
// 2014-2017 (Landsat): use tidal_early / nontidal_early
// 2018-2024 (Sentinel-2): use tidal / nontidal
// Training on 70% of samples, scale=10 matches package resolution

// --- For 2014-2017: use these two lines ---
var tidalFC    = ee.FeatureCollection("users/jianlingzhao3131/tidal_early")
                   .map(function(f){ return f.set('class', 1); });
var nonTidalFC = ee.FeatureCollection("users/jianlingzhao3131/nontidal_early")
                   .map(function(f){ return f.set('class', 0); });

// --- For 2018-2024: replace with these two lines ---
// var tidalFC    = ee.FeatureCollection("users/jianlingzhao3131/nontidal")
//                    .map(function(f){ return f.set('class', 1); });
// var nonTidalFC = ee.FeatureCollection("users/jianlingzhao3131/tidal")
//                    .map(function(f){ return f.set('class', 0); });

var samples = tidalFC.merge(nonTidalFC).randomColumn();

var training = featureStack.sampleRegions({
  collection: samples.filter(ee.Filter.lt('random', 0.7)),
  properties: ['class'],
  scale: 10,
  tileScale: 4
});

var rf       = ee.Classifier.smileRandomForest(100).train(training, 'class');
var rfResult = featureStack.classify(rf);

// 9. Apply candidate mask to RF result, then remove isolated patches
// mergedBeforeRF acts as spatial constraint: RF only runs within candidate zone
// rfResult.neq(0) keeps pixels classified as tidal flat (class=1)
// Final connectivity filter removes isolated patches smaller than 25 pixels
var finalTidalFlatRaw = mergedBeforeRF.updateMask(rfResult.neq(0));

// Remove isolated patches smaller than 25 connected pixels
var finalConnFilter = finalTidalFlatRaw.selfMask()
  .connectedPixelCount({maxSize: 26, eightConnected: true});
var finalTidalFlat = finalTidalFlatRaw.updateMask(finalConnFilter.gte(25));

// 10. Visualization
Map.addLayer(
  img.select(['B4','B3','B2']),
  {min: 0, max: 0.3},
  YEAR + ' True Color Base Map',
  true
);
Map.addLayer(
  mergedBeforeRF.selfMask(),
  {palette: ['blue'], opacity: 0.6},
  YEAR + ' Candidate Mask (Before RF)',
  false
);
Map.addLayer(
  finalTidalFlat.selfMask(),
  {palette: ['#E53935'], opacity: 0.8},
  YEAR + ' Final Tidal Flat',
  true
);
